spring:
  #mvc:
   # view:
    #  prefix: /WEB-INF/jsp/
   #   suffix: .jsp
  thymeleaf:
    cache: false   #关闭缓存
    #enabled: false  #关闭模板
    suffix: .html
    prefix: classpath:/templates/


  #配置数据库mysql数据源
  datasource:
    password: www.mysql.com
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://192.168.43.221:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://192.168.0.103:13306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true





item:
  name: 手机
  id=: 长跑ID
  color: 红色
  price: 2000
neo:
  title: 牛B
  description: 哈哈
other:
  title: keep smile
  blog: www.ityouknow.com

